language: go
go:
  - 1.x
before_install:
  - make tools
install:
  - # Prevent default install action "go get -t -v ./...".
script:
  - make ci
after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)
