language: go
go:
  - 1.x
before_install:
  - go get -u gopkg.in/alecthomas/gometalinter.v2
  - gometalinter.v2 --install
install:
  - # Prevent default install action "go get -t -v ./...".
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go tool vet .
  - go test -v -race ./...
  - gometalinter.v2 --skip=testdata --vendor ./...
